title: Jingyao Wu
description: 数学、猫与创造
lang: zh-CN
url: https://jingyaou.github.io
timezone: Asia/Shanghai
markdown: kramdown
permalink: /notes/:year/:month/:day/:title/

collections:
  knowledge:
    output: true
    permalink: /knowledge/:name/

defaults:
  - scope:
      path: ""
      type: knowledge
    values:
      layout: knowledge

exclude:
  - README.md
# GitHub Pages 自动构建随笔与知识库
